#!/usr/bin/env ruby

require 'csv'

class CppChecker
  def initialize(args)
    # Initialize command line args
    @csv_file = args[0]
  end

  def process
    CSV.open("output.csv", "wb") do |csv_out|
      CSV.foreach(@csv_file, headers: true) do |row|

        if row['Language'] == 'C++'
          # Write the Cpp file
          File.open('temp.cpp', 'w+') { |file| file.write(row['Code']) }

          # Run the check
          check_output = `./cpplint.py --counting=total temp.cpp`

        else
          # Write the C file
          File.open('temp.cc', 'w+') { |file| file.write(row['Code']) }

          # Run the check
          check_output = `./cpplint.py --counting=total temp.cc`

        end

        # Get the last word of the last line (error count)
        output = check_output.lines.last.split.last

        # Push the error count onto row
        row.push(output)

        # Write row to output csv
        csv_out << row
      end
    end
  end
end

CppChecker.new(ARGV).process
